---
ID: "604c88af-681d-4a73-9702-3d7607158f83"
Parent: "b8f01fe1-5430-4772-aff2-540b61ab7ab7"
Template: "b8f01fe1-5430-4772-aff2-540b61ab7ab7"
Path: /sitecore/templates/Feature/Events/_Event/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170626T150416Z
    - ID: "4dbf4835-5d8a-4650-a2ae-290a5aa7d597"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
